### PR TITLE
Added an option to pin if past offset

### PR DESCRIPTION
**Pull request by ginlime**

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Can I ask why? Could you not achieve this by using the `headroom--top` and `headroom--not-top` classes, and styling appropriately for each state (in your case, make visible?)

**Comment by WickyNilliams** [comment]
As an aside, it really helps the maintainer if you explain the *why* of your PR. Even if the code is simple, why you want to add it (e.g. what is the use case?) is just as (if not more) important than the code, in helping me understand the benefit of the addition

**Comment by ginlime** [comment]
Thanks for your reply.
It is very simple. The headroom.js determines the position where an header to be pinned or unpinned.
If it were not for "past offset" option, I shoud write more code to check the position. I'm afraid of being annoyed with occuring tug of war between headroom.js and my code.

I think the simpleness of code is very important, too. But, I think a simple solution is more important on coding.
I also think there are not a little needs to pin/unpin by passing a position, but I can't think up any sites for sample which behave like that (I'm so tired and sleepy...)

**Comment by WickyNilliams** [comment]
Not going to merge this, can't understand the reasoning behind it. 

However the commits for jQuery destroy would have fixed #130, if you'd like to make a separate PR for that?

**Pull request closed without merging**
