### PR TITLE
Fixes issue where feature-check for does not prevent .bind from being called

### PR DESCRIPTION
**Pull request by rajivm**
If function.bind is unavailable, headroom throws an exception trying to bind in the constructor.

Moved initialization of Debouncer to Headroom.init rather than the constructor.

### CODE REVIEW

**Comment by WickyNilliams** [comment]
I'm willing to merge this (sorry for the delay!!). 

@rajivm any chance you could merge bring your branch up to date and push, so that I can merge with the big green button? If not, let me know and I'll do myself at the command line. 

Also, you could remove the `if(this.initialised)` condition from the `destroy` method? removeEventListener  won't error if nothing has been registered (AFAIK).

**Comment by rajivm** [comment]
@WickyNilliams rebased, rebuilt, and made requested change. Let me know if this is good.

**Comment by joker-777** [comment]
Hi guys, we use an external tool to track js errors. We get quite a lot of the following error
>Object function (){var e=this.getScrollY(),t=e>this.lastKnownScrollY?"down":"up",n=this.toleranceExceeded(e,t);this.isOutOfBounds(e)||(e<=this.offset?this.top():this.notTop(),this.shouldUnpin(e,n)?this.unpin():this.shouldPin(e,n)&&this.pin(),this.lastKnownScrollY=e)} has no method 'bind'

Which I think is related to this PR. It would be nice if you could get this merged.

**Comment by rarkins** [comment]
Like @joker-777, I use an external tool to track JS errors and this became my number 1 source of daily errors. I've basically copied your own mustard cutting check to wrap the headroom JS init but would prefer it's inside instead.

**Comment by joker-777** [comment]
@WickyNilliams It would be great if you could merge this PR. Thanks!!

**Comment by gingerlime** [comment]
@WickyNilliams - you previously said you're willing to merge this after @rajivm applies some changes (which he did). Any thing else blocking from merging this?

**Comment by WickyNilliams** [comment]
The only thing blocking is I'm currently travelling in Asia with no computer. I'll be back at the end of the month and will get everything merged on my return

**Comment by hkdobrev** [comment]
@WickyNilliams ping.

**Comment by WickyNilliams** [comment]
I've fixed this on a local branch. Just waiting to get control of the headroom.js npm package (sigh), then I will push and publish

**Pull request closed without merging**
