### PR TITLE
Update dist folder for module support

### LINKED ISSUE #91: Publish to NPM?
That'd be nice for us Browserify users :)

Loving the library!

### PR DESCRIPTION
**Pull request by iDuuck**
Fixed #91 #97

### CODE REVIEW

**Comment by electerious** [comment]
@WickyNilliams Any chance to see this merged? Headroom is fantastic and adding module support would be a great addition.

**Comment by WickyNilliams** [comment]
I will do this myself when i cut the next release. @iDuuck could you please hand over control of the headroom.js npm package?

**Comment by electerious** [comment]
Glad to see new commits and an official npm package soon. Thanks for the work!

**Comment by chris-erickson** [comment]
Is it possible now to import this library once installed via npm?  Can anyone provide some hints of how to import headroom?

**Comment by WickyNilliams** [comment]
If you're using a bundler, it should just be a case of 

```js
var Headroom = require("headroom");
var hr = new Headroom(document.querySelector(".whatever"));
hr.init()
```

**Comment by chris-erickson** [comment]
Thanks - Is is possible to use this with the ES6 style `import`?  I'm a bit new to this, so I appreciate the help!

**Comment by WickyNilliams** [comment]
Yes it should be fine, combined with babel.

I believe it should just be a case of: 

`import Headroom from "headroom"`

If I were you, I would spend some time reading up on ES6 modules, before using a tool/feature you don't understand.

**Comment by chris-erickson** [comment]
Great, the first variant worked and it's nice to know the possible options.  New to an existing/inherited codebase, so lots to learn.  Thanks!! 🍻

**Comment by mitkovalkov** [comment]
This work fine for me 
`import Headroom from 'headroom.js';`

**Pull request closed without merging**
