### PR TITLE
Added a frozen option; headroom ignores interaction while frozen

### PR DESCRIPTION
**Pull request by rikvanmechelen**
Added an option to freeze headroom's state. When headroom has the frozen class set it will not update until the frozen class is taken off.
This could also cover #38

### CODE REVIEW

**Comment by DzmVasileusky** [comment]
+1 for this feature.
It can helps also in case spinned menu height more than window height.

**Comment by rikvanmechelen** [comment]
@WickyNilliams bump :)

**Comment by mfehrenbach** [comment]
@WickyNilliams This would be great for A/B testing libraries to turn headroom on and off, also. +1 from me.

**Comment by andreivictor** [comment]
+1

**Comment by WickyNilliams** [comment]
Closing, as superseded by #309

**Pull request closed without merging**
