### PR TITLE
Separate up/down offset values

### PR DESCRIPTION
**Pull request by matthewnessworthy**
Similar to https://github.com/WickyNilliams/headroom.js/pull/297 but up-to-date with the new version

Fixes https://github.com/WickyNilliams/headroom.js/issues/303

### CODE REVIEW

**Comment by matthewnessworthy** [comment]
@WickyNilliams would you mind taking a look when you get a chance please?

**Comment by matthewnessworthy** [comment]
@WickyNilliams would you mind taking a look when you get a chance please?

**Comment by WickyNilliams** [comment]
Excuse the delay! PR looks great, beautifully simple. I'm away from home without computer atm, will get a chance to merge on Monday.

**Comment by matthewnessworthy** [comment]
@WickyNilliams would you mind taking another look when you have a moment please?

**Review by WickyNilliams — APPROVED** [review]

**Comment by WickyNilliams** [comment]
Sorry about the delay! Just released as `v0.12.0`. Updated docs and changelog https://wicky.nillia.ms/headroom.js/#v0.12.0

**Comment by WickyNilliams** [comment]
Everything working OK for you, @matthewnessworthy?

**Comment by matthewnessworthy** [comment]
Everything is working great, thanks!

**Comment by WickyNilliams** [comment]
Awesome, glad to hear!

**Pull request merged**
