### PR TITLE
Fix: clear pending scrollTracker's timeout when the instance is destroyed

### LINKED ISSUE #338: Uncaught TypeError: Cannot read property 'destroy' of undefined
### Bug Report

Hello. I would like to report a bug in the latest version of Headroom.js. The problem is that in rare cases the `destroy` method can be called before `scrollTracker` has been initialized [in line #42](https://github.com/WickyNilliams/headroom.js/blob/master/src/Headroom.js#L42) due to putting it in the setTimeout callback which is not canceled when destroying the headroom instance.

#### Reproduction: https://jsfiddle.net/d20mxrbz/1/

### PR DESCRIPTION
**Pull request by sqal**
Fixes #338

### CODE REVIEW

**Comment by WickyNilliams** [comment]
@sqal thanks for this. I can't imagine you saw it, but I mentioned in a recent PR that I was thinking of dropping this async behaviour completely: https://github.com/WickyNilliams/headroom.js/pull/330#discussion_r321324405. This would simplify the code and flow of execution, and also avoid the kind of bug you've spotted here.

So with that in mind, I wonder whether it's worth just dropping setTimeout rather than fixing it up as you have done here.

@hacknug did you start on this by any chance?

**Comment by hacknug** [comment]
@WickyNilliams not yet, got caught up with client work 🥴

**Comment by WickyNilliams** [comment]
No worries! Just wanted to be sure there wasn't any duplication of effort. I think I'll do this today

**Comment by hacknug** [comment]
Go ahead. I'm in between projects and I'm not sure how much time I'll have to put in oss this week. Sorry!

**Comment by WickyNilliams** [comment]
Not a problem. As I'm sure you're aware, my participation in OSS is inconsistent and infrequent (to say the least haha), there's no expectation of any more than that :)

**Comment by sqal** [comment]
@WickyNilliams No, I hadn't seen your comment in the other PR before I opened mine. I guess we can close this PR now that you've done refactoring and this bug should be fixed? :)

**Comment by WickyNilliams** [comment]
@sqal yes, this can be closed now as i've just merged the PR removing the async behaviour. 

Thanks for highlighting this issue anyway, I really appreciate you taking the time to contribute :)

**Pull request closed without merging**
