### PR TITLE
Feature/multiple classes

### PR DESCRIPTION
**Pull request by WickyNilliams**
Rebased version of #348.

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Thanks @hacknug!

**Comment by hacknug** [comment]
Thanks for this, @WickyNilliams ❤️

**Comment by WickyNilliams** [comment]
No problems! Really appreciate the contribution

**Comment by WickyNilliams** [comment]
@hacknug if you'd like to continue to help out around here, I'm more than happy to give you contributor permissions. No pressure to be super active of course. It is up to you, no worries if not :)

**Comment by hacknug** [comment]
@WickyNilliams don't worry, I've been quite busy for the past weeks and haven't had much time for OSS. I'll open issues and PRs first always to discuss so no need to be able to push directly 👍

**Comment by WickyNilliams** [comment]
I just thought it might be a nice gesture as a thank you, and recognition of the time and effort you've put in. There'd be zero obligations - I wouldn't have any expectation of you being active or doing anything really. But if you felt the need, then you could do so freely. Or close issues etc. I would prevent merge to master anyway so PRs would be necessary still. 

But like I say, no worries if not, just wanted to reiterate to be clear on expectations :)

**Comment by hacknug** [comment]
Okay. Let's do this then haha

**Comment by WickyNilliams** [comment]
You should have now received an invite!

I've setup the repo so that reviews on PRs are required. I understand that this prevents pushes to master. 

I don't think there's a great deal of granularity for access rights if a repo is owned by a user (versus an org), so you can pretty much do anything. Use the power wisely :)

**Pull request merged**
